### ISSUE TITLE
关于qwen2的最大训练长度问题

### ISSUE THREAD

**Issue by WeixuanXiong** [yuyijiong/train_with_paraphrasing#1]
请问您用Qlora+transformers的正常方式可以在32k的上下文长度下启动qwen2-7b的训练吗？

**Comment by yuyijiong** [comment]
好像必须在loss计算后把logits设为None才可以

**Comment by WeixuanXiong** [comment]
> 好像必须在loss计算后把logits设为None才可以
请问您用的GPU是什么型号呢，我这边用80G的A800会OOM，在zero3+flashattn全开的情况也会。

**Comment by yuyijiong** [comment]
单卡用zero3是没用的。
flash attention 2肯定是必须开的。
如果在loss计算后把logits设为None还是不行，那就把logits转float32那句话删除，让logits保持bf16的dtype。但是有一定概率会训崩

**Comment by yuyijiong** [comment]
实在不行就截断到28k长度，效果也差不多

**Comment by WeixuanXiong** [comment]
logits设为None指的是把transformers库里面的trainer函数改一下嘛？

**Comment by yuyijiong** [comment]
[qwen2](https://github.com/yuyijiong/train_with_paraphrasing/blob/main/model_train/modeling_qwen2_training.py)
看这个代码里的forward函数，我改过。其实就是修改Qwen2ForCausalLM的forward函数

**Comment by WeixuanXiong** [comment]
好的，感谢回复~
